[bigmailer]
BRAND_ID = "61969b8a-a1ff-4c52-9225-e9d59b65714e"
API_KEY = "d0577226-c57a-42b2-b921-ca9b9367b480"

[lists]
MAIN = "f8279af2-8947-48d7-a5b3-87ab35675404"
WARMING1 = "2085bf1c-2fde-4fe4-a9c7-ccb36bd00459"
WARMING2 = "c440fda0-02fc-49cd-b6b3-bb8cce48cc46"
WARMING3 = "43843072-1cb2-489f-86fc-0fea4304035d"
WARMING4 = "7d7b4148-49bd-4706-85bd-a264a50b50d0"
WARMING5 = "641fb003-638a-431f-ad08-b50243bce761"

[google]
SPREADSHEET_ID = "1hy3UtwszcJbO5vXJxwWBVGG9sRm2beI8vaXeUw_qQhY"
SERVICE_ACCOUNT_JSON = \"\"\"{
  \"type\": \"service_account\",
  \"project_id\": \"dev-order-450504-t0\",
  \"private_key_id\": \"1c9793ed278aa2b79d40238e98466f3c3d5d207b\",
  \"private_key\": \"-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkq...\\n-----END PRIVATE KEY-----\\n\",
  \"client_email\": \"bigmailerbot@dev-order-450504-t0.iam.gserviceaccount.com\",
  \"client_id\": \"101929602118108514282\",
  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",
  \"token_uri\": \"https://oauth2.googleapis.com/token\",
  \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",
  \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/bigmailerbot%40dev-order-450504-t0.iam.gserviceaccount.com\",
  \"universe_domain\": \"googleapis.com\"
}\"\"\"